FROM python:3.9

ENV DEBUG False

ENV TZ Asia/Kolkata

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./app /code/app
