version: "3.9"

services:
  daksh_v2_web_server_build:
    build:
      context: .
      dockerfile: Dockerfile
    image: gcr.io/avl-data-archiver/daksh-v2-webserver:latest

  daksh_v2_web_server:
    stdin_open: true
    tty: true
    restart: always
    image: gcr.io/avl-data-archiver/daksh-v2-webserver:latest
    container_name: daksh_v2_web_server
    working_dir: /code
    entrypoint:
      - /bin/bash
      - -c
      - |
          uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    networks:
      - daksh-v2-web-server
    depends_on:
      - "influxdb"
    deploy:
      resources:
        limits:
          memory: 1000M
          cpus: '2'
    cpuset: '24,25'

  telegraf:
    stdin_open: true
    tty: true
    image: telegraf
    container_name: telegraf
    restart: always
    networks:
      - daksh-v2-web-server
    volumes:
     - ./conf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
     - /var/run/docker.sock:/var/run/docker.sock:ro
     - /sys:/rootfs/sys:ro
     - /proc:/rootfs/proc:ro
     - /etc:/rootfs/etc:ro
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
    depends_on:
      - "influxdb"
    deploy:
      resources:
        limits:
          memory: 1000M
          cpus: '2'
    cpuset: '30,31'


  influxdb:
    stdin_open: true
    tty: true
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    networks:
      - daksh-v2-web-server
    #volumes:
    #  - influxdb-volume:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=iot_device
      - INFLUXDB_USER=telegraf
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=avl_influxdb123!@#
    deploy:
      resources:
        limits:
          memory: 1000M
          cpus: '4'
    cpuset: '26,27,28,29'



networks:
  daksh-v2-web-server:

volumes:
  influxdb-volume:
    external: true
