version: '3.3'

services:
  daksh_v2_tag_management:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GIT_USERNAME: ${GIT_USERNAME}
        GIT_PASSWORD: ${GIT_PASSWORD}
    image: daksh_v2_tag_management:latest

  daksh_v2_tag_management_dev:
    stdin_open: true
    tty: true
    restart: always
    image: daksh_v2_tag_management:latest
    container_name: daksh_v2_tag_management_dev
    env_file:
      - .env
      - Docker/env/${DAKSH_V2_TAG_MANAGEMENT_ENV}.env
    working_dir: /root/src/daksh_v2_tag_management
    entrypoint:
      - /bin/bash
      - -c
      - |
          #sleep infinity
          python3 manage.py runserver --insecure 0.0.0.0:9102 #Insecure helps us serve static with Debug = False, since this is the dev container, this is intentional.
    ports:
        - "9102:9102"
    networks:
      daksh_v2_tag_management:
        ipv4_address: ${DAKSH_V2_TAG_MANAGEMENT_IP}
    volumes:
        - .:/root/src/daksh_v2_tag_management
    healthcheck:
      test: "curl -f -s -o /dev/null -I http://${DAKSH_V2_TAG_MANAGEMENT_IP}:9102/login/"
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      - "postgres_daksh_v2_tag_management"

  daksh_v2_tag_management_prod:
    stdin_open: true
    tty: true
    restart: always
    image: daksh_v2_tag_management:latest
    container_name: daksh_v2_tag_management_prod
    env_file:
      - .env
      - Docker/env/${DAKSH_V2_TAG_MANAGEMENT_ENV}.env
    working_dir: /root/src/daksh_v2_tag_management
    entrypoint:
      - /bin/bash
      - -c
      - |
          gunicorn daksh_v2_tag_management.wsgi -b 0.0.0.0:9102 --workers 2 -k gthread --threads 16 --timeout 300 --log-level info --limit-request-line 8190 --access-logfile -
    ports:
      - "9102:9102"
    networks:
      daksh_v2_tag_management:
        ipv4_address: ${DAKSH_V2_TAG_MANAGEMENT_IP}
    volumes:
      - .:/root/src/daksh_v2_tag_management
    healthcheck:
      test: "curl -f -s -o /dev/null -I http://${DAKSH_V2_TAG_MANAGEMENT_IP}:9102/login/"
      interval: 10s
      timeout: 10s
      retries: 5
    logging:
      options:
        tag: "{{.Name}} {{.ImageName}}"
    depends_on:
      - "postgres_daksh_v2_tag_management"

  daksh_v2_tag_management_init:
    stdin_open: true
    tty: true
    image: daksh_v2_tag_management:latest
    container_name: daksh_v2_tag_management_init
    env_file:
      - .env
      - Docker/env/${DAKSH_V2_TAG_MANAGEMENT_ENV}.env
    working_dir: /root/src/daksh_v2_tag_management
    entrypoint:
      - /bin/bash
      - -c
      - |
          rm -rf static
          python3 manage.py collectstatic --noinput && \
          python3 manage.py avlmigrate -d && \
          python3 manage.py avlmigrate -i && \
          python3 manage.py makemigrations && \
          python3 manage.py migrate && \
          echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(email='${DAKSH_V2_TAG_MANAGEMENT_SU_EMAIL}').delete(); User.objects.create_superuser('admin', '${DAKSH_V2_TAG_MANAGEMENT_SU_EMAIL}', '${DAKSH_V2_TAG_MANAGEMENT_SU_PASS}')" | python3 manage.py shell
    ports:
      - "9102:9102"
    networks:
      daksh_v2_tag_management:
        ipv4_address: ${DAKSH_V2_TAG_MANAGEMENT_IP}
    volumes:
      - .:/root/src/daksh_v2_tag_management
    depends_on:
      - "postgres_daksh_v2_tag_management"

  daksh_v2_tag_management_analytics:
    stdin_open: true
    tty: true
    restart: always
    image: daksh_v2_tag_management:latest
    container_name: daksh_v2_tag_management_analytics
    env_file:
      - .env
      - Docker/env/${DAKSH_V2_TAG_MANAGEMENT_ENV}.env
    working_dir: /root/src/daksh_v2_tag_management/notebooks
    entrypoint:
      - /bin/bash
      - -c
      - |
          python3 ../manage.py shell_plus --notebook;
    ports:
      - "8893:8888"
    networks:
      daksh_v2_tag_management:
        ipv4_address: ${DAKSH_V2_TAG_MANAGEMENT_ANALYTICS_IP}
    volumes:
      - .:/root/src/daksh_v2_tag_management
    healthcheck:
      test: "curl -f -s -o /dev/null -I http://${DAKSH_V2_TAG_MANAGEMENT_ANALYTICS_IP}:8888/"
      interval: 10s
      timeout: 10s
      retries: 5
    logging:
      options:
        tag: "{{.Name}} {{.ImageName}}"

  daksh_v2_tag_management_analytics_readonly:
    stdin_open: true
    tty: true
    restart: always
    image: daksh_v2_tag_management:latest
    container_name: daksh_v2_tag_management_analytics_readonly
    env_file:
      - .env
      - Docker/env/analytics.env
    working_dir: /root/src/daksh_v2_tag_management/notebooks
    entrypoint:
      - /bin/bash
      - -c
      - |
        python3 ../manage.py shell_plus --notebook;
    ports:
      - "8892:8888"
    networks:
      daksh_v2_tag_management:
        ipv4_address: ${DAKSH_V2_TAG_MANAGEMENT_ANALYTICS_READONLY_IP}
    volumes:
      - .:/root/src/daksh_v2_tag_management
    healthcheck:
      test: "curl -f -s -o /dev/null -I http://${DAKSH_V2_TAG_MANAGEMENT_ANALYTICS_READONLY_IP}:8888/"
      interval: 10s
      timeout: 10s
      retries: 5
    logging:
      options:
        tag: "{{.Name}} {{.ImageName}}"

  postgres_daksh_v2_tag_management:
    stdin_open: true
    tty: true
    restart: always
    image: postgres_daksh_v2_tag_management:latest
    container_name: postgres_daksh_v2_tag_management
    entrypoint: postgres -c 'config_file=/etc/postgresql.conf'
    user: postgres
    env_file:
      - .env
      - Docker/env/${DAKSH_V2_TAG_MANAGEMENT_ENV}.env
    ports:
      - "5436:5432"
    volumes:
      - postgres_daksh_v2_tag_management_volume:/var/lib/postgresql/data/pgdata
      - ./Docker/postgresdb/postgresql.conf:/etc/postgresql.conf
    networks:
      daksh_v2_tag_management:
        ipv4_address: ${DAKSH_V2_TAG_MANAGEMENT_POSTGRES_IP}
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U ${DAKSH_V2_TAG_MANAGEMENT_POSTGRES_USER} -d ${DAKSH_V2_TAG_MANAGEMENT_POSTGRES_DB}"
      interval: 10s
      timeout: 10s
      retries: 5

networks:
  daksh_v2_tag_management:
    external:
      name: daksh_v2_tag_management

volumes:
  postgres_daksh_v2_tag_management_volume:
    external: true
