FROM python:3.9.1
RUN apt-get update
RUN pip install pandas
#ADD /home/manik/postgres_comm10k.py 
#RUN pip install psycopg2==2.9.2
#RUN pip install psycopg2-binary==2.9.2
#RUN pip install paho-mqtt==1.6.1
#RUN pwd
#CMD [ "python", "/service.py"]
