version: '3.3'

services:
  postgres_daksh_api:
    stdin_open: true
    tty: true
    build: .
    image: postgres_daksh_api:latest
    container_name: postgres_daksh_api
    env_file:
      - .env
      - ../env/${DAKSH_API_FRAMEWORK_ENV}.env
    ports:
      - "5438:5432"
    volumes:
      - postgres_daksh_api_volume:/var/lib/postgresql/data/pgdata
    networks:
      daksh_api_framework:
        ipv4_address: ${DAKSH_API_POSTGRES_IP}

  postgres_host:
    image: postgres_daksh_api:latest
    env_file:
      - .env
      - ../env/${DAKSH_API_FRAMEWORK_ENV}.env
    container_name: postgres_daksh_api_host
    entrypoint: /root/restore-dump.sh
    volumes:
      - .:/root/
    networks:
      - daksh_api_framework
    depends_on:
      - "postgres_daksh_api"

networks:
  daksh_api_framework:
    external:
      name: daksh_api_framework

volumes:
  postgres_daksh_api_volume:
    external: true