from django.db import models

class Report(models.Model):
    date_time = models.CharField(max_length=50)
    device = models.CharField(max_length=50)
    frequency = models.CharField(max_length=50)
    voltage_ph1 = models.CharField(max_length=50)
    voltage_ph2 = models.CharField(max_length=50)
    voltage_ph3 = models.CharField(max_length=50)
    voltage_ph1_ph2 = models.CharField(max_length=50)
    voltage_ph2_ph3 = models.CharField(max_length=50)
    voltage_ph3_ph1 = models.CharField(max_length=50)
    current_ph1 = models.CharField(max_length=50)
    current_ph2 = models.CharField(max_length=50)
    current_ph3 = models.CharField(max_length=50)
    cuurent_avg = models.CharField(max_length=50)
    active_power = models.CharField(max_length=50)
    total_energy= models.CharField(max_length=50)
    power_factor = models.CharField(max_length=50)
    thd_voltage = models.CharField(max_length=50)
    thd_current_i1 = models.CharField(max_length=50)
    thd_current_i2 = models.CharField(max_length=50)
    thd_current_i3 = models.CharField(max_length=50)
    import_energy= models.CharField(max_length=50)
    export_energy= models.CharField(max_length=50)
    date_time_min = models.CharField(max_length=50)
    date_time_py = models.DateTimeField(null=True, blank=True)

class Schedule(models.Model):
    scheduling_time = models.DateTimeField()
    report_type = models.CharField(max_length=50)
    frequency = models.CharField(max_length=50)
    duration = models.CharField(max_length=50)
    id = models.CharField(max_length=7,primary_key=True)
    recipient = models.TextField(null=True, blank=True)
    selected_rows = models.TextField(null=True, blank=True)
    day = models.CharField(max_length=5,null=True, blank=True)
    date = models.DateField(null=True)
    time = models.TimeField(null=True)